'use client';
import { useCallback, useEffect, useState } from 'react';
import { useGameTools } from '@/lib/game-tools';
import GamePlayer from './games';
import { Gamepad2, Search, Shuffle, ArrowUpRight, LayoutGrid, Puzzle, Zap, Brain, MousePointer2, Heart, Sparkles, ChevronRight, Play } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { Input } from '@/components/ui/input';
import { Dialog, DialogContent, DialogTitle, DialogDescription } from '@/components/ui/dialog';

export const games = [
 {id:'2048',name:'2048',category:'Puzzle',desc:'Small tiles. Big possibilities.',color:'peach',tag:'FAN FAVORITE',tiles:['2','4','','','8','16','4','','','32','64','8','','','128','256']},
 {id:'snake',name:'Snake',category:'Arcade',desc:'One more bite. One more try.',color:'mint',tag:'CLASSIC',tiles:['','','','','','','●','●','●','','','','●','','','◆']},
 {id:'memory',name:'Memory Match',category:'Brain',desc:'Find your perfect match.',color:'lavender',tag:'',tiles:['✿','?','◆','?','?','✿','?','◆']},
 {id:'tictactoe',name:'Tic Tac Toe',category:'Strategy',desc:'A friendly battle of Xs and Os.',color:'pink',tag:'2 PLAYERS',tiles:['×','○','','','×','○','','','×']},
 {id:'mines',name:'Minesweeper',category:'Strategy',desc:'A little logic. A little courage.',color:'blue',tag:'',tiles:['1','1','','','1','⚑','','','2','2','1','','','','','']},
 {id:'scramble',name:'Word Scramble',category:'Brain',desc:'A twist on your daily word fix.',color:'yellow',tag:'',tiles:['P','L','A','Y']},
 {id:'reaction',name:'Reaction Time',category:'Quick play',desc:'How quick is your click?',color:'purple',tag:'QUICK BREAK',tiles:['ϟ']},
 {id:'whack',name:'Pop a Dot',category:'Arcade',desc:'Catch the dots. Beat the clock.',color:'orange',tag:'',tiles:['','●','','','','●','','●','']},
 {id:'lights',name:'Lights Out',category:'Puzzle',desc:'Make every light go dark.',color:'navy',tag:'',tiles:['●','','●','','●','●','','●','●','','●','','','','●','']},
 {id:'fifteen',name:'Slide 15',category:'Puzzle',desc:'Everything in its right place.',color:'teal',tag:'',tiles:['1','2','3','4','5','6','7','8','9','10','11','12','13','','14','15']},
 {id:'simon',name:'Color Echo',category:'Brain',desc:'Watch. Remember. Repeat.',color:'rose',tag:'',tiles:['','','','']},
 {id:'math',name:'Quick Math',category:'Quick play',desc:'Give your brain a little sprint.',color:'lime',tag:'',tiles:['7','+','5','=','?']},
];
export type Game = typeof games[number];
const categories=[{name:'All games',icon:LayoutGrid},{name:'Arcade',icon:Gamepad2},{name:'Puzzle',icon:Puzzle},{name:'Brain',icon:Brain},{name:'Strategy',icon:MousePointer2},{name:'Quick play',icon:Zap}];
export function GameArt({game,large=false}:{game:Game,large?:boolean}) {return <div className={`game-art ${game.color} art-${game.id} ${large?'large':''}`} aria-hidden="true"><div className="mini-board">{game.tiles.map((t,i)=><span key={i} className={`tile tile-${i} ${t?'filled':''}`}>{t}</span>)}</div></div>}
export default function Home(){
 const [category,setCategory]=useState('All games');const [query,setQuery]=useState('');const [active,setActive]=useState<Game|null>(null);const [favorites,setFavorites]=useState<string[]>([]);const [ready,setReady]=useState(false);
 useEffect(()=>{try{const saved=JSON.parse(localStorage.getItem('pocket-favorites')||'[]');if(Array.isArray(saved))setFavorites(saved.filter(x=>typeof x==='string'));}catch{}setReady(true)},[]);
 useEffect(()=>{if(ready)try{localStorage.setItem('pocket-favorites',JSON.stringify(favorites))}catch{}},[favorites,ready]);
 const openGame=useCallback((id:string)=>setActive(games.find(g=>g.id===id)||null),[]);
 useGameTools(games,openGame);
 const visible=games.filter(g=>(category==='All games'||category==='Favorites'&&favorites.includes(g.id)||g.category===category)&&g.name.toLowerCase().includes(query.toLowerCase()));
 const random=()=>setActive(games[Math.floor(Math.random()*games.length)]);
 return <><aside className="sidebar"><a className="brand" href="/" aria-label="Pocket Arcade home"><span className="brand-icon"><Gamepad2 size={25}/></span><span>pocket<span className="brand-sub">ARCADE</span></span></a><div className="nav-label">LET'S PLAY</div><nav>{categories.map(({name,icon:Icon})=><button key={name} onClick={()=>setCategory(name)} className={category===name?'selected':''}><Icon size={20}/>{name}{name==='All games'&&<span className="count">12</span>}</button>)}</nav><div className="nav-divider"/><nav><button onClick={()=>setCategory('Favorites')} className={category==='Favorites'?'selected':''}><Heart size={20}/>My favorites<span className="count">{favorites.length}</span></button><button onClick={random}><Shuffle size={20}/>Surprise me</button></nav><div className="sidebar-note"><span className="little-spark">✦</span><strong>A little play goes a long way.</strong><p>Your next good break starts here.</p><span className="free-note"><span/>Always free to play</span></div><div className="sidebar-bottom">Small games. Big happy.</div></aside>
 <div className="shell"><header className="topbar"><span className="breadcrumb">Your everyday escape <span>✦</span></span><label className="search"><Search size={18}/><Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Find your next favorite game" aria-label="Search games"/></label><span className="top-free"><span/>100% free. No sign-up.</span></header><main><div className="page-heading"><div className="eyebrow">PRESS PAUSE. PLAY SOMETHING.</div><h1>Good times, <span>one game away.</span></h1><p>Pick a game. Find your flow. Stay for one more round.</p></div><section className="feature-grid" aria-label="Featured games"><div className="featured"><div className="feature-copy"><span className="feature-kicker"><Sparkles size={14}/> THE DAILY DISTRACTION</span><h2>Just one.<br/>More. Tile.</h2><p>Meet your next tiny obsession.<br/>Slide, merge, and chase 2048.</p><Button className="play-main" onClick={()=>setActive(games[0])}><Play size={16} fill="currentColor"/>Play 2048<ArrowUpRight size={18}/></Button><span className="feature-meta">PUZZLE <span>•</span> EASY TO LEARN</span></div><GameArt game={games[0]} large/></div><div className="surprise-panel"><span className="surprise-icon"><Shuffle size={34}/></span><span className="eyebrow">FEELING SPONTANEOUS?</span><h2>Let play<br/>find you.</h2><p>A new favorite could be<br/>one click away.</p><Button onClick={random}>Surprise me<ArrowUpRight size={17}/></Button><span className="corner-star">✳</span></div></section>
 <section className="library"><div className="section-title"><h2>{category==='All games'?'Find your kind of fun':category}<span>{visible.length} games</span></h2><span className="ready-label"><Zap size={15}/> Ready when you are</span></div><div className="category-tabs">{categories.map(({name,icon:Icon})=><Button variant="outline" className={category===name?'active':''} key={name} onClick={()=>setCategory(name)}><Icon size={16}/>{name}</Button>)}</div><div className="games-grid">{visible.map(g=><article className="game-card" key={g.id}><button className="card-play" onClick={()=>setActive(g)} aria-label={`Play ${g.name}`}><GameArt game={g}/>{g.tag&&<span className="game-tag">{g.tag}</span>}<span className="play-overlay"><Play size={23} fill="currentColor"/></span></button><div className="card-info"><div><button onClick={()=>setActive(g)} className="game-name">{g.name}</button><p>{g.desc}</p></div><button className={`favorite ${favorites.includes(g.id)?'is-favorite':''}`} aria-label={`${favorites.includes(g.id)?'Remove':'Add'} ${g.name} ${favorites.includes(g.id)?'from':'to'} favorites`} onClick={()=>setFavorites(v=>v.includes(g.id)?v.filter(x=>x!==g.id):[...v,g.id])}><Heart size={18} fill={favorites.includes(g.id)?'currentColor':'none'}/></button></div><div className="card-meta">{g.category}<span>Free to play <ChevronRight size={13}/></span></div></article>)}</div>{!visible.length&&<div className="empty"><Search/><h3>{category==='Favorites'?'Your favorites live here':'No games found'}</h3><p>{category==='Favorites'?'Tap a heart on any game to save it on this device.':'Try a different name or category.'}</p><Button onClick={()=>{setQuery('');setCategory('All games')}}>Explore all games</Button></div>}</section><footer><span><Gamepad2 size={19}/>pocket arcade</span><p>No downloads. No paywalls. Just play.</p><span>Made for your little breaks ✦</span></footer></main></div>
 <Dialog open={!!active} onOpenChange={open=>{if(!open)setActive(null)}}><DialogContent className="game-modal">{active&&<><DialogTitle className="modal-title">{active.name}</DialogTitle><DialogDescription>{active.desc} Free to play, always.</DialogDescription><GamePlayer game={active}/></>}</DialogContent></Dialog></>
}



